### ISSUE TITLE
Repeat test case dataset

### ISSUE THREAD

**Issue by rklehm-xc** [Xceptance/neodymium-library#61] opened 2018-10-10 09:37 UTC
One can pass the -Dsurefire.rerunFailingTestsCount=<fixed repeat count> at test execution in order to repeat failed test cases. As several test case datasets are knew to fail sometimes the test developer wants to mark them as "to be repeated". I suggest an annotation:

@RepeatDataSetOnFail{}

**Comment by occupant23** [comment] 2018-12-05 08:49
Is a duplicate of #53 and. Further discussions in the other issue.

**Closed by occupant23** 2018-12-05 08:49 UTC
Labels: Low Priority, duplicate, feature
